using System.IO;
using System.Security.Cryptography;
using System.Windows.Controls;
using System.Windows.Threading;
using MemoApp.Core.Editing;
using MemoApp.Core.Storage;
using MemoApp.Windows;
internal static partial class Program
{
    private static async Task AutomaticBackupPersistenceRun()
    {
        string area=Path.Combine(Path.GetTempPath(),"memo-wpf-persistent-auto-"+Guid.NewGuid().ToString("N")),root=Path.Combine(area,"vault"),output=Path.Combine(area,"output");Directory.CreateDirectory(output);
        byte[] secret=EncryptedVault.GenerateRecoverySecret();Guid profile=Guid.NewGuid();MainWindow? main=null;
        async Task CloseWindow(){if(main is null)return;var active=Field<SaveCoordinator?>(main,"session");if(active is not null&&!active.IsLocked)await active.LockAsync();if(active?.PendingKind is not null and not "none"){active.Dispose();SetField(main,"session",null!);}else Invoke(main,"ReleaseSettledSession");SetField(main,"confirmedExit",true);main.Close();main=null;}
        void Open(EncryptedVault vault){main=new MainWindow(root,profile);main.Show();Invoke(main,"StartSession",vault);Field<DispatcherTimer>(main,"timer").Stop();}
        Task<bool> Configure()=>InvokeAsync("ConfigurePersistentAutomaticBackupsAsync",output,20,false,true,false);
        Task<bool> InvokeAsync(string name,params object?[] args){var method=typeof(MainWindow).GetMethod(name,System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);Require(method is not null,"Persistent automatic backup API missing: "+name);return(Task<bool>)method!.Invoke(main,args)!;}
        try
        {
            Open(EncryptedVault.Create(root,secret,secret));Require(Control<CheckBox>(main!,"AutoBackupPersist").IsChecked!=true,"Persistence starts explicitly off");Require(await Configure(),"Explicit encrypted opt-in saves before activation");await CloseWindow();
            Open(EncryptedVault.Open(root,secret));Require(Field<object?>(main!,"automaticBackup") is not null&&Control<CheckBox>(main!,"AutoBackupPersist").IsChecked==true,"Same profile/root/current restores persisted policy");
            DateOnly day=DateOnly.FromDateTime(DateTime.UtcNow);Require(await InvokeAsync("RunAutomaticBackupAtAsync",false,day,null),"First daily attempt writes encrypted backup");await CloseWindow();
            Open(EncryptedVault.Open(root,secret));Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day,null)&&Directory.GetFiles(output).Length==1,"Restart cannot repeat reserved UTC day");Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(-1),null),"Clock rollback cannot repeat a day");
            Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(1),new RefusingAutomaticCopyFiles()),"Copy failure still consumes persisted day");await CloseWindow();Open(EncryptedVault.Open(root,secret));Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(1),null),"Failed copy reservation survives restart");
            var failedReservation=Field<SaveCoordinator>(main!,"session");var bad=failedReservation.Workspace.CreateNote();bad.Title=new string('q',257);Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(2),null)&&Directory.GetFiles(output).Length==1,"Invalid draft rejects the entire reservation candidate and creates no backup");Require(failedReservation.Workspace.GetUiDevice(profile).AutomaticBackupPolicy!.LastAttemptDay==day.AddDays(1),"Rejected reservation preflight leaves the previous policy day unchanged");Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(2),null),"Failed reservation attempt is throttled within the current runtime");bad.Title="repaired daily fixture";Require(await failedReservation.SaveAsync(),"Explicit repair saves the unchanged prior reservation policy");await CloseWindow();Open(EncryptedVault.Open(root,secret));Require(Field<SaveCoordinator>(main!,"session").Workspace.GetUiDevice(profile).AutomaticBackupPolicy!.LastAttemptDay==day.AddDays(1),"Restart restores only the last committed day after rejected preflight");
            var restarted=Field<SaveCoordinator>(main!,"session");var referencedRecentTask=Field<Task>(main!,"recentTask");
            var restartedList=Control<ListBox>(main!,"NotesList");var restartedSelection=restarted.Workspace.Notes.Single();
            Require(restartedList.SelectedItems.Count==1&&ReferenceEquals(restartedList.SelectedItem,restartedSelection),"Restart selects the exact repaired current note before recent work settles");
            await Idle();await referencedRecentTask;
            Require(ReferenceEquals(Field<Task>(main!,"recentTask"),referencedRecentTask)&&referencedRecentTask.IsCompletedSuccessfully&&Field<object?>(main!,"pendingRecent") is null,"Actual tracked restart recent work settles before the explicit daily attempt");
            Require(ReferenceEquals(Field<SaveCoordinator>(main!,"session"),restarted)&&!restarted.IsLocked&&restartedList.SelectedItems.Count==1&&ReferenceEquals(restartedList.SelectedItem,restartedSelection)&&restarted.Workspace.GetUiDevice(profile).RecentNoteIds.FirstOrDefault()==restartedSelection.Id,"Settled recent work belongs to the exact current restart selection");
            Require(restarted.Workspace.GetUiDevice(profile).AutomaticBackupPolicy!.LastAttemptDay==day.AddDays(1)&&Field<DateOnly?>(main!,"automaticBackupAttemptDay")==day.AddDays(1),"Settling restart selection does not reserve the explicit next backup day");
            string RestartState()
            {
                var policyDay=restarted.Workspace.GetUiDevice(profile).AutomaticBackupPolicy?.LastAttemptDay;
                var attemptDay=Field<DateOnly?>(main!,"automaticBackupAttemptDay");
                return $"runtimePresent={Field<object?>(main!,"automaticBackup") is not null} busy={restarted.IsBusy} dirty={restarted.IsDirty} locked={restarted.IsLocked} generationSavedEqual={Field<long>(restarted,"generation")==Field<long>(restarted,"savedGeneration")} recentTaskTerminal={Field<Task>(main!,"recentTask").IsCompleted} sameRecentTask={ReferenceEquals(referencedRecentTask,Field<Task>(main!,"recentTask"))} referencedRecentTerminal={referencedRecentTask.IsCompleted} pendingRecent={Field<object?>(main!,"pendingRecent") is not null} recentCount={restarted.Workspace.GetUiDevice(profile).RecentNoteIds.Length} selectionCount={Control<ListBox>(main!,"NotesList").SelectedItems.Count} policyPriorDay={policyDay==day.AddDays(1)} policyTargetDay={policyDay==day.AddDays(2)} attemptPriorDay={attemptDay==day.AddDays(1)} attemptTargetDay={attemptDay==day.AddDays(2)}";
            }
            string beforeRestartAttempt=RestartState();bool restartAttempt=await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(2),null);int restartFileCount=Directory.GetFiles(output).Length;
            if(!restartAttempt||restartFileCount!=2)Console.Error.WriteLine($"AUTO_BACKUP_RESTART_DIAGNOSTIC before[{beforeRestartAttempt}] after[{RestartState()}] returned={restartAttempt} fileCount={restartFileCount}");
            Require(restartAttempt&&restartFileCount==2,"Restart permits the day that was never committed and reserves it before copying");Require(!await InvokeAsync("RunAutomaticBackupAtAsync",false,day.AddDays(2),null),"Successful retry consumes its committed UTC day");
            Require(await InvokeAsync("DisableAutomaticBackupsAsync"),"Explicit OFF is saved");await CloseWindow();Open(EncryptedVault.Open(root,secret));Require(Field<object?>(main!,"automaticBackup") is null&&Field<SaveCoordinator>(main!,"session").Workspace.GetUiDevice(profile).AutomaticBackupPolicy is null,"OFF survives restart");
            Require(await Configure(),"Re-enable policy");
            var hidden=Field<SaveCoordinator>(main!,"session");var invalid=hidden.Workspace.CreateNote();Guid hiddenNote=invalid.Id;invalid.Title=new string('x',257);Require(!await hidden.LockAsync()&&hidden.PendingKind=="plaintext-hidden","Synthetic invalid draft enters hidden recovery");hidden.ResumeHidden(secret);Invoke(main!,"ShowEditing");Require(Field<object?>(main!,"automaticBackup") is null&&hidden.Workspace.GetUiDevice(profile).AutomaticBackupPolicy is not null,"Hidden resume retains encrypted setting without activating runtime");hidden.Workspace.Notes.Single(n=>n.Id==hiddenNote).Title="repaired synthetic";Require(await hidden.SaveAsync(),"Hidden draft repaired and saved");await CloseWindow();
            using(var recovery=EncryptedVault.Open(root,secret)){var snapshot=recovery.Loaded;var first=snapshot.UiDevices.Single(d=>d.UiDeviceId==profile);var second=first with{UiDeviceId=Guid.NewGuid()};recovery.Save(snapshot with{UiDevices=[first,second]});}
            string candidateName="previous-"+Guid.NewGuid().ToString("N")+".vault",candidatePath=Path.Combine(root,candidateName);File.Copy(Path.Combine(root,"current.vault"),candidatePath);byte[] candidateBytes=File.ReadAllBytes(candidatePath);main=new MainWindow(root,profile);
            var recovered=(Task<EncryptedVault>)typeof(MainWindow).GetMethod("SaveRecoveredVaultAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[EncryptedVault.Open(root,secret,candidateName),secret])!;
            using(var sanitized=await recovered){Require(sanitized.Loaded.UiDevices.All(d=>d.AutomaticBackupPolicy is null),"Explicit recovery sanitizes every profile before reopen");Require(File.ReadAllBytes(candidatePath).SequenceEqual(candidateBytes),"Recovery preserves candidate encrypted bytes");}SetField(main,"confirmedExit",true);main.Close();main=null;
            Open(EncryptedVault.Open(root,secret));Require(await Configure(),"Recovery requires explicit fresh opt-in");await CloseWindow();string copied=Path.Combine(area,"copied");Directory.CreateDirectory(copied);foreach(string file in Directory.GetFiles(root))File.Copy(file,Path.Combine(copied,Path.GetFileName(file)));root=copied;Open(EncryptedVault.Open(root,secret));Require(Field<object?>(main!,"automaticBackup") is null&&Field<SaveCoordinator>(main!,"session").Workspace.GetUiDevice(profile).AutomaticBackupPolicy is not null,"Copied vault stays inactive and retains encrypted DTO for reselection");
            await CloseWindow();await AutomaticPersistentOffRaceRun();await AutomaticPersistentCopyOffRun();await AutomaticPersistentRejectedConfigurationRun();await AutomaticPersistentReservationWriteFailureRun();
        }
        finally{await CloseWindow();CryptographicOperations.ZeroMemory(secret);Directory.Delete(area,true);}
    }
    private static async Task AutomaticPersistentOffRaceRun()
    {
        string area=Path.Combine(Path.GetTempPath(),"memo-wpf-persist-race-"+Guid.NewGuid().ToString("N")),root=Path.Combine(area,"vault"),output=Path.Combine(area,"output");Directory.CreateDirectory(output);byte[] secret=EncryptedVault.GenerateRecoverySecret();MainWindow? main=null;var paused=new PausedAutomaticCommitFiles();
        try
        {
            main=new MainWindow(root);main.Show();Invoke(main,"StartSession",EncryptedVault.Create(root,secret,secret,paused));Field<DispatcherTimer>(main,"timer").Stop();var configure=typeof(MainWindow).GetMethod("ConfigurePersistentAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!;var pending=(Task<bool>)configure.Invoke(main,[output,20,false,true,false])!;
            await paused.Entered.Task.WaitAsync(TimeSpan.FromSeconds(10));Require(!await(Task<bool>)configure.Invoke(main,[output,20,true,false,true])!,"Busy reconfiguration rejects and revokes pending ON authority");Require(!await(Task<bool>)typeof(MainWindow).GetMethod("RunAutomaticBackupAtAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[false,DateOnly.FromDateTime(DateTime.UtcNow),null])!,"Revoked configuration cannot reserve or copy daily metadata");var off=(Task<bool>)typeof(MainWindow).GetMethod("DisableAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[])!;Require(Field<object?>(main,"automaticBackup") is null,"OFF revokes runtime before pending encrypted save settles");paused.Continue.TrySetResult();Require(!await pending&&await off&&Field<object?>(main,"automaticBackup") is null,"Late ON cannot override explicit OFF");
        }
        finally{paused.Continue.TrySetResult();if(main is not null){var active=Field<SaveCoordinator?>(main,"session");if(active is not null&&!active.IsLocked)await active.LockAsync();if(active?.PendingKind is not null and not "none"){active.Dispose();SetField(main,"session",null!);}else Invoke(main,"ReleaseSettledSession");SetField(main,"confirmedExit",true);main.Close();}CryptographicOperations.ZeroMemory(secret);Directory.Delete(area,true);}
    }
    private static async Task AutomaticPersistentCopyOffRun()
    {
        string area=Path.Combine(Path.GetTempPath(),"memo-wpf-copy-off-"+Guid.NewGuid().ToString("N")),root=Path.Combine(area,"vault"),output=Path.Combine(area,"output");Directory.CreateDirectory(output);byte[] secret=EncryptedVault.GenerateRecoverySecret();MainWindow? main=null;var paused=new PausedAutomaticCommitFiles();
        try
        {
            main=new MainWindow(root);main.Show();Invoke(main,"StartSession",EncryptedVault.Create(root,secret,secret));Field<DispatcherTimer>(main,"timer").Stop();Require(await(Task<bool>)typeof(MainWindow).GetMethod("ConfigurePersistentAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[output,20,false,true,true])!,"Copy-off fixture opt-in");
            var adapter=typeof(MainWindow).GetNestedType("CapacityCheckedBackupFiles",System.Reflection.BindingFlags.NonPublic)!;var fieldTypes=adapter.GetFields(System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Public).Select(f=>f.FieldType).ToArray();Require(fieldTypes.All(t=>t==typeof(string)||t==typeof(Guid)||t==typeof(int)||t==typeof(IAtomicVaultFiles)||t==typeof(CancellationToken)),"Detached ciphertext adapter contains only scalar paths/limits, files and standalone cancellation token");
            var pending=(Task<bool>)typeof(MainWindow).GetMethod("RunAutomaticBackupAtAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[false,DateOnly.FromDateTime(DateTime.UtcNow),paused])!;await paused.Entered.Task.WaitAsync(TimeSpan.FromSeconds(10));Require(await(Task<bool>)typeof(MainWindow).GetMethod("DisableAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[])!,"OFF persists while detached CreateNew is paused");paused.Continue.TrySetResult();Require(!await pending&&Directory.GetFiles(output).All(p=>new FileInfo(p).Length==0),"Late CreateNew after OFF writes no ciphertext and cannot reactivate runtime");var active=Field<SaveCoordinator>(main,"session");Require(await(Task<bool>)typeof(MainWindow).GetMethod("LockForCloseAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[active])!&&active.KeysReleased&&Directory.GetFiles(output).All(p=>new FileInfo(p).Length==0),"Revoked exit configuration locks without creating backup");
        }
        finally{paused.Continue.TrySetResult();if(main is not null){var active=Field<SaveCoordinator?>(main,"session");if(active is not null&&!active.IsLocked)await active.LockAsync();if(active?.PendingKind is not null and not "none"){active.Dispose();SetField(main,"session",null!);}else Invoke(main,"ReleaseSettledSession");SetField(main,"confirmedExit",true);main.Close();}CryptographicOperations.ZeroMemory(secret);Directory.Delete(area,true);}
    }
    private static async Task AutomaticPersistentRejectedConfigurationRun()
    {
        string area=Path.Combine(Path.GetTempPath(),"memo-wpf-reconfigure-"+Guid.NewGuid().ToString("N")),root=Path.Combine(area,"vault"),output=Path.Combine(area,"output");Directory.CreateDirectory(output);byte[] secret=EncryptedVault.GenerateRecoverySecret();MainWindow? main=null;var files=new GatedAutomaticCommitFiles();
        try
        {
            main=new MainWindow(root);main.Show();Invoke(main,"StartSession",EncryptedVault.Create(root,secret,secret,files));Field<DispatcherTimer>(main,"timer").Stop();var configure=typeof(MainWindow).GetMethod("ConfigurePersistentAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!;Require(await(Task<bool>)configure.Invoke(main,[output,20,false,true,true])!,"Active reconfiguration fixture baseline");files.PauseNext=1;var run=typeof(MainWindow).GetMethod("RunAutomaticBackupAtAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!;DateOnly today=DateOnly.FromDateTime(DateTime.UtcNow);var pending=(Task<bool>)run.Invoke(main,[false,today,null])!;await files.Entered.Task.WaitAsync(TimeSpan.FromSeconds(10));Require(!await(Task<bool>)configure.Invoke(main,[output,20,true,false,true])!&&Field<object?>(main,"automaticBackup") is null,"Rejected busy configuration immediately revokes active runtime");files.Continue.TrySetResult();Require(!await pending&&!await(Task<bool>)run.Invoke(main,[false,today.AddDays(1),null])!&&Directory.GetFiles(output).Length==0,"Revoked daily completion cannot copy or reserve a later stale day");var active=Field<SaveCoordinator>(main,"session");Require(active.Workspace.Capture().UiDevices.Single(d=>d.AutomaticBackupPolicy is not null).AutomaticBackupPolicy!.LastAttemptDay==today,"Rejected runtime cannot mutate stored reservation after revocation");Require(await(Task<bool>)typeof(MainWindow).GetMethod("LockForCloseAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[active])!&&active.KeysReleased&&Directory.GetFiles(output).Length==0,"Revoked exit authority cannot copy");
        }
        finally{files.Continue.TrySetResult();if(main is not null){var active=Field<SaveCoordinator?>(main,"session");if(active is not null&&!active.IsLocked)await active.LockAsync();if(active?.PendingKind is not null and not "none"){active.Dispose();SetField(main,"session",null!);}else Invoke(main,"ReleaseSettledSession");SetField(main,"confirmedExit",true);main.Close();}CryptographicOperations.ZeroMemory(secret);Directory.Delete(area,true);}
    }
    private sealed class GatedAutomaticCommitFiles:IAtomicVaultFiles
    {
        private readonly AtomicVaultFiles actual=new();internal int PauseNext;internal readonly TaskCompletionSource Entered=new(TaskCreationOptions.RunContinuationsAsynchronously),Continue=new(TaskCreationOptions.RunContinuationsAsynchronously);
        public Stream CreateNew(string path){if(Interlocked.Exchange(ref PauseNext,0)==1){Entered.TrySetResult();if(!Continue.Task.Wait(TimeSpan.FromSeconds(10)))throw new IOException("Synthetic source commit pause");}return actual.CreateNew(path);}
        public void FlushToDisk(Stream stream)=>actual.FlushToDisk(stream);public void Move(string temporary,string current)=>actual.Move(temporary,current);public void Replace(string temporary,string current,string previous)=>actual.Replace(temporary,current,previous);
    }
    private static async Task AutomaticPersistentReservationWriteFailureRun()
    {
        string area=Path.Combine(Path.GetTempPath(),"memo-wpf-reservation-write-failure-"+Guid.NewGuid().ToString("N")),root=Path.Combine(area,"vault"),output=Path.Combine(area,"output");Directory.CreateDirectory(output);byte[] secret=EncryptedVault.GenerateRecoverySecret();Guid profile=Guid.NewGuid();MainWindow? main=null;var files=new FailingReservationCommitFiles();
        async Task CloseWindow(){if(main is null)return;var active=Field<SaveCoordinator?>(main,"session");if(active is not null&&!active.IsLocked)await active.LockAsync();if(active?.PendingKind is not null and not "none"){active.Dispose();SetField(main,"session",null!);}else Invoke(main,"ReleaseSettledSession");SetField(main,"confirmedExit",true);main.Close();main=null;}
        void Open(EncryptedVault vault){main=new MainWindow(root,profile);main.Show();Invoke(main,"StartSession",vault);Field<DispatcherTimer>(main,"timer").Stop();}
        try
        {
            Open(EncryptedVault.Create(root,secret,secret,files));Require(await(Task<bool>)typeof(MainWindow).GetMethod("ConfigurePersistentAutomaticBackupsAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!.Invoke(main,[output,20,false,true,false])!,"Actual reservation write-failure fixture baseline");DateOnly today=DateOnly.FromDateTime(DateTime.UtcNow);var run=typeof(MainWindow).GetMethod("RunAutomaticBackupAtAsync",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!;files.FailNext=1;
            Require(!await(Task<bool>)run.Invoke(main,[false,today,null])!&&files.FailureReached&&Directory.GetFiles(output).Length==0,"Actual source commit failure after valid reservation creates no backup");var active=Field<SaveCoordinator>(main!,"session");Require(active.Workspace.GetUiDevice(profile).AutomaticBackupPolicy!.LastAttemptDay==today&&active.PendingKind=="ciphertext","Reservation was accepted and encrypted before the injected disk failure");Require(!await(Task<bool>)run.Invoke(main,[false,today,null])!,"Failed reservation write is throttled within its runtime");Require(Control<TextBlock>(main!,"Notice").Text.Contains("예약을 저장하지 못해"),"Failed reservation write truthfully reports no backup");await CloseWindow();
            Open(EncryptedVault.Open(root,secret));Require(Field<SaveCoordinator>(main!,"session").Workspace.GetUiDevice(profile).AutomaticBackupPolicy!.LastAttemptDay is null,"Restart retains the last committed policy without inventing a failed reservation day");Require(await(Task<bool>)run.Invoke(main,[false,today,null])!&&Directory.GetFiles(output).Length==1,"Restart can commit the previously failed reservation before creating its backup");await CloseWindow();Open(EncryptedVault.Open(root,secret));Require(!await(Task<bool>)run.Invoke(main,[false,today,null])!&&Directory.GetFiles(output).Length==1,"Only the successfully committed reservation survives restart and suppresses its day");
        }
        finally{await CloseWindow();CryptographicOperations.ZeroMemory(secret);Directory.Delete(area,true);}
    }
    private sealed class FailingReservationCommitFiles:IAtomicVaultFiles
    {
        private readonly AtomicVaultFiles actual=new();internal int FailNext;internal bool FailureReached;
        public Stream CreateNew(string path){if(Interlocked.Exchange(ref FailNext,0)==1){FailureReached=true;throw new IOException("Synthetic reservation source commit failure");}return actual.CreateNew(path);}
        public void FlushToDisk(Stream stream)=>actual.FlushToDisk(stream);public void Move(string temporary,string current)=>actual.Move(temporary,current);public void Replace(string temporary,string current,string previous)=>actual.Replace(temporary,current,previous);
    }
    private sealed class RefusingAutomaticCopyFiles:IAtomicVaultFiles
    {public Stream CreateNew(string path)=>throw new IOException("Synthetic copy failure");public void FlushToDisk(Stream stream)=>throw new IOException();public void Move(string temporary,string current)=>throw new NotSupportedException();public void Replace(string temporary,string current,string previous)=>throw new NotSupportedException();}
}
