using System.Text.Json;
using System.Text.Json.Nodes;
using MemoApp.Core.Storage;
internal static class AttachmentContractChecks
{
    private static VaultSnapshot Decode(JsonObject json)
    {try{using var document=JsonDocument.Parse(json.ToJsonString());SnapshotValidation.Json(document.RootElement);var snapshot=JsonSerializer.Deserialize<VaultSnapshot>(json.ToJsonString(),VaultEnvelope.JsonOptions)!;VaultEnvelope.Validate(snapshot);return snapshot;}catch(JsonException){throw new InvalidDataException("Invalid structural attachment JSON");}}
    internal static void Run()
    {
        // Structural fixtures deliberately contain dummy ciphertext; this unit does not claim AEAD validation.
        var now=DateTimeOffset.UtcNow;var noteId=Guid.NewGuid();var rootId=Guid.NewGuid();var objectId=Guid.NewGuid();
        var basis=new VaultSnapshot(4,Guid.NewGuid(),[new(noteId,Guid.NewGuid(),[],now,now,"synthetic","body")]);
        var json=JsonSerializer.SerializeToNode(basis,VaultEnvelope.JsonOptions)!.AsObject();json["schemaVersion"]=5;json["attachmentRootId"]=rootId.ToString();json["notes"]![0]!["attachmentIds"]=new JsonArray(objectId.ToString());
        json["attachmentObjects"]=new JsonArray(new JsonObject{["objectId"]=objectId.ToString(),["rootId"]=rootId.ToString(),["name"]="합성.pdf",["mime"]="application/pdf",["length"]=1,["sha256"]=new string('0',64),["wrappedKey"]=Convert.ToBase64String(new byte[60]),["chunks"]=new JsonArray(Convert.ToBase64String(new byte[65552]))});
        var decoded=Decode(json);VaultChecks.Require(decoded.SchemaVersion==5,"valid bounded attachment schema5 metadata and references");
        void Reject(Action<JsonObject> edit,string reason){var altered=(JsonObject)json.DeepClone();edit(altered);VaultChecks.ExpectFailure(()=>Decode(altered),reason);}
        Reject(p=>p.Remove("attachmentRootId"),"v5 root identity required");Reject(p=>p.Remove("attachmentObjects"),"v5 object array required");Reject(p=>p["notes"]![0]!.AsObject().Remove("attachmentIds"),"v5 note refs required");Reject(p=>p["attachmentRootId"]=Guid.Empty.ToString(),"empty root identity");
        Reject(p=>p["attachmentObjects"]![0]!["rootId"]=Guid.NewGuid().ToString(),"wrong object root");Reject(p=>p["notes"]![0]!["attachmentIds"]=new JsonArray(Guid.NewGuid().ToString()),"foreign object reference");Reject(p=>p["notes"]![0]!["attachmentIds"]=new JsonArray(objectId.ToString(),objectId.ToString()),"duplicate note refs");Reject(p=>p["attachmentObjects"]!.AsArray().Add(p["attachmentObjects"]![0]!.DeepClone()),"duplicate object ID");
        Reject(p=>p["attachmentObjects"]![0]!["name"]="../unsafe.pdf","metadata filename cannot become path");VaultChecks.ExpectFailure(()=>VaultEnvelope.Validate(decoded with{AttachmentObjects=[decoded.AttachmentObjects[0] with{Name="bad\uD800"}]}),"typed malformed filename rejected before JSON replacement");Reject(p=>p["attachmentObjects"]![0]!["mime"]="text/unsafe\r\n","MIME control characters");Reject(p=>p["attachmentObjects"]![0]!["mime"]="application/pdf\n","MIME final LF cannot bypass regex anchor");Reject(p=>p["attachmentObjects"]![0]!["length"]=-1,"negative original length");Reject(p=>p["attachmentObjects"]![0]!["length"]=4194305,"object4MiB limit");Reject(p=>p["attachmentObjects"]![0]!["length"]=65537,"chunk-count/length relation");Reject(p=>p["attachmentObjects"]![0]!["sha256"]="not-a-hash","original hash format");Reject(p=>p["attachmentObjects"]![0]!["sha256"]=new string('0',64)+"\n","hash final LF cannot bypass regex anchor");
        Reject(p=>p["attachmentObjects"]![0]!["wrappedKey"]="short","wrap encoded-length preflight");Reject(p=>p["attachmentObjects"]![0]!["chunks"]![0]="short","chunk encoded-length preflight");Reject(p=>p["attachmentObjects"]![0]!["extra"]=true,"unknown typed object fields");Reject(p=>p["schemaVersion"]=4,"legacy cannot carry nonempty attachment state");
        var empty=(JsonObject)json.DeepClone();empty["attachmentObjects"]![0]!["length"]=0;_ = Decode(empty);
        var unreferenced=(JsonObject)json.DeepClone();unreferenced["notes"]![0]!["attachmentIds"]=new JsonArray();_ = Decode(unreferenced);
        Reject(p=>{var array=p["attachmentObjects"]!.AsArray();var example=array[0]!.DeepClone();array.Clear();for(int index=0;index<129;index++){var item=example.DeepClone();item["objectId"]=Guid.NewGuid().ToString();array.Add(item);}},"all retained objects count128 bound");
        Reject(p=>{var array=p["attachmentObjects"]!.AsArray();var refs=new JsonArray();var example=array[0]!.DeepClone();array.Clear();for(int index=0;index<17;index++){var id=Guid.NewGuid().ToString();var item=example.DeepClone();item["objectId"]=id;array.Add(item);refs.Add(id);}p["notes"]![0]!["attachmentIds"]=refs;},"per-note references16 bound");
        Reject(p=>{var array=p["attachmentObjects"]!.AsArray();var example=array[0]!.DeepClone();example["length"]=4194304;var chunks=new JsonArray();for(int index=0;index<64;index++)chunks.Add(Convert.ToBase64String(new byte[65552]));example["chunks"]=chunks;array.Clear();for(int index=0;index<3;index++){var item=example.DeepClone();item["objectId"]=Guid.NewGuid().ToString();array.Add(item);}p["notes"]![0]!["attachmentIds"]=new JsonArray();},"retained unreferenced objects still count aggregate8MiB bound");
        Reject(p=>p["attachmentObjects"]![0]!["chunks"]![0]=new string('A',87404),"decoded exact length/padding canonical base64 check");
        var historyId=Guid.NewGuid();var withHistory=(JsonObject)json.DeepClone();withHistory["notes"]![0]!["parents"]=new JsonArray(historyId.ToString());withHistory["history"]=new JsonArray(new JsonObject{["noteId"]=noteId.ToString(),["revisionId"]=historyId.ToString(),["parents"]=new JsonArray(),["modifiedAt"]=now.ToString("O"),["title"]="old",["text"]="old body",["mode"]="plain",["document"]=null,["metadata"]=withHistory["notes"]![0]!["metadata"]!.DeepClone(),["attachmentIds"]=new JsonArray(objectId.ToString())});_ = Decode(withHistory);var missing=(JsonObject)withHistory.DeepClone();missing["history"]![0]!.AsObject().Remove("attachmentIds");VaultChecks.ExpectFailure(()=>Decode(missing),"v5 immutable history refs required");
        for(int schema=1;schema<=4;schema++){var legacy=new VaultSnapshot(schema,Guid.NewGuid(),[]);using var encoded=JsonDocument.Parse(SnapshotSerialization.Bytes(legacy));VaultChecks.Require(!encoded.RootElement.TryGetProperty("attachmentRootId",out _)&&!encoded.RootElement.TryGetProperty("attachmentObjects",out _),"legacy actual serializer omits unsupported root/object fields");}
        using(var encoded=JsonDocument.Parse(SnapshotSerialization.Bytes(basis)))VaultChecks.Require(!encoded.RootElement.GetProperty("notes")[0].TryGetProperty("attachmentIds",out _),"legacy actual note serialization omits unsupported references");
        var imageDocument=new MemoApp.Core.Documents.StyledDocument(1,"{\"nodes\":[{\"type\":\"image\",\"attachmentId\":\""+objectId+"\"}]}");
        VaultChecks.ExpectFailure(()=>VaultEnvelope.Validate(decoded with{Notes=[decoded.Notes.Single() with{Mode="rich",Document=imageDocument}]}),"schema5 image-node refs require a separate complete integration gate");
        var historical=Decode(withHistory);VaultChecks.ExpectFailure(()=>VaultEnvelope.Validate(historical with{History=[historical.History.Single() with{Mode="rich",Document=imageDocument}]}),"schema5 historical image-node refs cannot silently pass note-only reference checks");
        var nested=new MemoApp.Core.Documents.StyledDocument(1,"{\"nodes\":[{\"type\":\"future-node\",\"opaque\":{\"attachmentIds\":[]}}]}");
        VaultChecks.ExpectFailure(()=>VaultEnvelope.Validate(decoded with{Notes=[decoded.Notes.Single() with{Mode="rich",Document=nested}]}),"schema5 opaque nested attachment-like refs explicitly blocked until understood");
        VaultEnvelope.Validate(basis with{Notes=[basis.Notes.Single() with{Mode="rich",Document=imageDocument}]});
        Console.WriteLine("PASS: structural schema5 attachment metadata/ref/Unicode/base64/count/length bounds and immutable history/unreferenced retention policy (dummy ciphertext; not crypto proof)");
    }
}
