using System.Buffers.Binary;
using System.IO.Compression;
using System.Reflection;
using System.Runtime.ExceptionServices;
using System.Security.Cryptography;
using MemoApp.Core.Storage;
internal static class PngDecoderChecks
{
    private delegate object Decode(ReadOnlySpan<byte> source,CancellationToken cancellation,Action<byte[]>? allocations);
    private delegate void Pixels(ReadOnlySpan<byte> pixels);
    internal static void Run()
    {
        var type=typeof(EncryptedVault).Assembly.GetType("MemoApp.Core.Transfer.PngPixelDecoder");VaultChecks.Require(type is not null,"Strict bounded PNG pixel decoder is missing");
        var decode=type!.GetMethod("Decode",BindingFlags.NonPublic|BindingFlags.Static)!.CreateDelegate<Decode>();
        foreach(int channels in new[]{1,2,3,4})foreach(int filter in Enumerable.Range(0,5))
        {
            int width=5,height=3;var original=Enumerable.Range(0,width*height*channels).Select(i=>(byte)((i*53+177)%256)).ToArray();if(channels is 2 or 4){original[channels-1]=0;original[2*channels-1]=255;}
            var raw=Filtered(original,width,height,channels,filter);var compressed=Compress(raw,CompressionLevel.SmallestSize);var source=Png(width,height,channels,[compressed]);var copy=(byte[])source.Clone();var scratch=new List<byte[]>();using var raster=(IDisposable)decode(source,default,scratch.Add);
            byte[] owned=Owned(raster);VaultChecks.Require(Scalar(raster,"Width")==width&&Scalar(raster,"Height")==height&&Scalar(raster,"Stride")==width*4,"Exact bounded raster scalars");
            var expected=Bgra(original,channels);VaultChecks.Require(owned.SequenceEqual(expected),"Independent five-filter grayscale/gray-alpha/RGB/RGBA exact BGRA oracle including wrap/alpha");VaultChecks.Require(scratch.Where(x=>!ReferenceEquals(x,owned)).All(x=>x.All(b=>b==0)),"Success zeroes all owned compressed/row scratch");
            VaultChecks.Require(Consume(raster,span=>VaultChecks.Require(span.SequenceEqual(expected),"Borrowed detached pixels are exact"))&&owned.All(b=>b==0),"Single raster consumption zeroes actual owned output");VaultChecks.ExpectFailure(()=>Consume(raster,_=>{}),"Repeated pixel consume refused");VaultChecks.Require(source.SequenceEqual(copy),"Pixel decode never mutates original input");
            foreach(int split in new[]{1,compressed.Length-2}){using var splitRaster=(IDisposable)decode(Png(width,height,channels,[compressed[..split],[],compressed[split..]]),default,null);VaultChecks.Require(Owned(splitRaster).SequenceEqual(expected),"IDAT split including trailer is transparent to zlib input");}
        }
        foreach(var tie in new[]{(2,254,7),(1,255,4)}){byte[] filtered=[0,(byte)tie.Item1,0,0,3,0,0,4,(byte)tie.Item2,0,0,(byte)tie.Item3,0,0];byte[] expected=[0,0,(byte)tie.Item1,255,0,0,3,255,0,0,0,255,0,0,7,255];using var tied=(IDisposable)decode(Png(2,2,3,[Compress(filtered,CompressionLevel.SmallestSize)]),default,null);VaultChecks.Require(Owned(tied).SequenceEqual(expected),"Explicit independent Paeth a/c then b/c tie precedence pixel oracle");}
        byte[] storedVector=[0x78,0x01,0x01,0x05,0x00,0xfa,0xff,0,1,2,3,4,0,0x19,0,0x0b];using(var vector=(IDisposable)decode(Png(1,1,4,[storedVector]),default,null))VaultChecks.Require(Owned(vector).SequenceEqual(new byte[]{3,2,1,4}),"Independent hand-authored RFC stored-block zlib/Adler vector");
        var widePixels=Enumerable.Range(0,2050*2*4).Select(i=>(byte)(i%251)).ToArray();using(var wide=(IDisposable)decode(Png(2050,2,4,[Compress(Filtered(widePixels,2050,2,4,0),CompressionLevel.SmallestSize)]),default,null)){VaultChecks.Require(Scalar(wide,"Width")==1024&&Scalar(wide,"Height")==1&&Scalar(wide,"Stride")==4096,"Aspect floor/no enlargement scalar agreement");var output=Owned(wide);for(int x=0;x<1024;x++){int start=(int)((long)x*2050/1024)*4;VaultChecks.Require(output[x*4]==widePixels[start+2]&&output[x*4+1]==widePixels[start+1]&&output[x*4+2]==widePixels[start]&&output[x*4+3]==widePixels[start+3],"Independent nearest-neighbor downsample mapping");}}
        foreach(int channels in new[]{1,2})
        {
            int width=2050,height=3;var sourcePixels=Enumerable.Range(0,width*height*channels).Select(i=>(byte)((i*71+31)%256)).ToArray();var png=Png(width,height,channels,[Compress(Filtered(sourcePixels,width,height,channels,4),CompressionLevel.SmallestSize)]);using var raster=(IDisposable)decode(png,default,null);var output=Owned(raster);
            VaultChecks.Require(Scalar(raster,"Width")==1024&&Scalar(raster,"Height")==1,"Grayscale downsample dimensions remain aspect-floor bounded");for(int x=0;x<1024;x++){int from=(int)((long)x*width/1024)*channels;VaultChecks.Require(output[x*4]==sourcePixels[from]&&output[x*4+1]==sourcePixels[from]&&output[x*4+2]==sourcePixels[from]&&output[x*4+3]==(channels==2?sourcePixels[from+1]:255),"Exact nearest-neighbor gray/alpha expansion before owned raster publication");}
            byte[] raw=Filtered(sourcePixels,width,height,channels,0),compressed=Compress(raw,CompressionLevel.SmallestSize);var badAdler=(byte[])compressed.Clone();badAdler[^1]^=1;Reject(Png(width,height,channels,[badAdler]),"Grayscale corrupted Adler refused with all allocated buffers zeroed");Reject(Png(width,height,channels,[[..compressed,0]]),"Grayscale trailing zlib byte refused");Reject(Png(width,height,channels,[Compress(raw[..^1],CompressionLevel.SmallestSize)]),"Grayscale short decoded row refused");Reject(Png(width,height,channels,[Compress([..raw,0],CompressionLevel.SmallestSize)]),"Grayscale overlong decoded raster refused");raw[0]=5;Reject(Png(width,height,channels,[Compress(raw,CompressionLevel.SmallestSize)]),"Grayscale invalid filter refused");
            var tiny=Png(1,1,channels,[Compress(new byte[channels+1],CompressionLevel.SmallestSize)]);for(int at=1;at<=4;at++){using var cancelAt=new CancellationTokenSource();var scratch=new List<byte[]>();ExpectCanceled(()=>decode(tiny,cancelAt.Token,bytes=>{scratch.Add(bytes);if(scratch.Count==at)cancelAt.Cancel();}),"Gray/alpha cancellation at every allocation boundary");VaultChecks.Require(scratch.Count==at&&scratch.All(bytes=>bytes.All(b=>b==0)),"Gray/alpha cancellation zeroes all exact owned allocations");}
        }
        foreach(var shape in new[]{(1,4096),(4096,1),(2048,2048)}){int width=shape.Item1,height=shape.Item2;using var full=(IDisposable)decode(Png(width,height,4,[Compress(new byte[(width*4+1)*height],CompressionLevel.SmallestSize)]),default,null);VaultChecks.Require(Owned(full).Length==Scalar(full,"Width")*Scalar(full,"Height")*4&&Owned(full).Length<=4194304&&Owned(full).All(b=>b==0),"Exact axes/source-pixel/output bounds with actual decode");}
        var adapterType=type.GetNestedType("ExactZlibInput",BindingFlags.NonPublic)!;using(var adapter=(Stream)Activator.CreateInstance(adapterType,BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance,null,[new byte[]{1,2,3},CancellationToken.None],null)!){var bytes=new byte[8];VaultChecks.Require(adapter.Read(bytes,0,0)==0&&adapter.Read(bytes,0,8)==1&&bytes[0]==1&&adapter.Read(bytes.AsSpan())==1&&bytes[0]==2&&adapter.ReadByte()==3,"All nonempty adapter paths supply exactly one byte");VaultChecks.ExpectFailure(()=>adapter.ReadByte(),"Adapter never returns ordinary EOF before verified inflater completion");}
        var scanline=new byte[]{0,1,2,3,4};foreach(var level in new[]{CompressionLevel.NoCompression,CompressionLevel.Fastest,CompressionLevel.SmallestSize}){using var raster=(IDisposable)decode(Png(1,1,4,[Compress(scanline,level)]),default,null);VaultChecks.Require(Owned(raster).SequenceEqual(new byte[]{3,2,1,4}),"BCL compression-level round trips decode equally (block type not inferred)");}
        byte[] fixedVector=Convert.FromHexString("7801636064626601000019000b");byte[] dynamicVector=Convert.FromHexString("78dad5d5c10d84301004c1c6c69cb1c93fde43b331f403695fad557d07cef9f4df7eaf5deb786fdc9c77d5a76aab3aaaceaabbea51b59056c82864e61dd10e8d688746b4534d3b34a21d1ad14e45b4f38e688736edd088762aa21d1ad10e8d68a722da7947b44323daa111ed54a63c697479d2d8f2a4717d7dd298f2a4d1e54963c993c6f8faa431e549a3c993c692278d214fda1fa53f47fb");VaultChecks.Require(((fixedVector[2]>>1)&3)==1&&((dynamicVector[2]>>1)&3)==2,"Independent Python-zlib1.3.2 vectors prove actual fixed/dynamic first block types");
        using(var fixedRaster=(IDisposable)decode(Png(1,1,4,[fixedVector]),default,null))VaultChecks.Require(Owned(fixedRaster).SequenceEqual(new byte[]{3,2,1,4}),"Independent fixed-Huffman pixel vector");var dynamicPixels=Enumerable.Range(0,32*32*3).Select(i=>(byte)((i*17+i/7)%13)).ToArray();using(var dynamicRaster=(IDisposable)decode(Png(32,32,3,[dynamicVector]),default,null))VaultChecks.Require(Owned(dynamicRaster).SequenceEqual(Bgra(dynamicPixels,3)),"Independent dynamic-Huffman exact RGB oracle");for(int n=0;n<dynamicVector.Length;n++)Reject(Png(32,32,3,[dynamicVector[..n]]),"Every independent dynamic-Huffman truncation refused");Reject(Png(32,32,3,[[..dynamicVector,0]]),"Independent dynamic trailing byte refused");
        var zlib=Compress(scanline,CompressionLevel.SmallestSize);
        for(int n=0;n<zlib.Length;n++)Reject(Png(1,1,4,[zlib[..n]]),"Every compressed byte truncation refused");
        foreach(int i in Enumerable.Range(zlib.Length-4,4)){var bad=(byte[])zlib.Clone();bad[i]^=1;Reject(Png(1,1,4,[bad]),"Each Adler trailer corruption refused");}
        Reject(Png(1,1,4,[[1,2,3]]),"Valid structure with bad compression refused");Reject(Png(1,1,4,[[..zlib,0]]),"Compressed trailing byte refused");Reject(Png(1,1,4,[[..zlib,..zlib]]),"Concatenated zlib stream refused");
        Reject(Png(1,1,4,[Compress([..scanline,0],CompressionLevel.SmallestSize)]),"Exact raster budget rejects one extra decompressed byte");Reject(Png(1,1,4,[Compress(scanline[..4],CompressionLevel.SmallestSize)]),"Short decompressed row refused");Reject(Png(1,1,4,[Compress([5,1,2,3,4],CompressionLevel.SmallestSize)]),"Invalid filter refused");
        var dictionary=(byte[])zlib.Clone();dictionary[1]=(byte)(dictionary[1]|32);for(int f=0;f<256;f++)if((f&32)!=0&&((dictionary[0]<<8)+f)%31==0){dictionary[1]=(byte)f;break;}Reject(Png(1,1,4,[dictionary]),"Preset dictionary refused with valid header modulus");
        var cancel=new CancellationToken(true);var canceledScratch=new List<byte[]>();ExpectCanceled(()=>decode(Png(1,1,4,[zlib]),cancel,canceledScratch.Add),"Canceled before allocations");VaultChecks.Require(canceledScratch.Count==0,"Pre-cancel allocation refusal");
        for(int at=1;at<=4;at++){using var cancellation=new CancellationTokenSource();var scratch=new List<byte[]>();ExpectCanceled(()=>decode(Png(1,1,4,[zlib]),cancellation.Token,bytes=>{scratch.Add(bytes);if(scratch.Count==at)cancellation.Cancel();}),"Cancellation at every allocation boundary");VaultChecks.Require(scratch.Count==at&&scratch.All(x=>x.All(b=>b==0)),"Cancellation refuses further allocations and zeroes all prior owned buffers");}
        using(var cancellation=new CancellationTokenSource()){var scratch=new List<byte[]>();ExpectCanceled(()=>decode(Png(1,1,4,[zlib]),cancellation.Token,bytes=>{scratch.Add(bytes);cancellation.Cancel();}),"Allocation-time cancellation before decode");VaultChecks.Require(scratch.All(x=>x.All(b=>b==0)),"Cancellation finally-zeroes actual allocations");}
        using(var cancellation=new CancellationTokenSource()){var scratch=new List<byte[]>();ExpectCanceled(()=>decode(Png(1,1,4,[zlib]),cancellation.Token,bytes=>{scratch.Add(bytes);if(scratch.Count==4){VaultChecks.Require(scratch[0].Any(b=>b!=0),"Late-cancel fixture has loaded genuine compressed scratch");cancellation.Cancel();}}),"Cancellation after all owned allocations");VaultChecks.Require(scratch.Count==4&&scratch.All(x=>x.All(b=>b==0)),"Late cancellation zeroes loaded compressed/rows/output");}
        {var scratch=new List<byte[]>();VaultChecks.ExpectFailure(()=>decode(Png(1,1,4,[zlib]),default,bytes=>{scratch.Add(bytes);if(scratch.Count==4)throw new IOException("Synthetic allocation observer failure");}),"Observer exception after result allocation");VaultChecks.Require(scratch.Count==4&&scratch.All(x=>x.All(b=>b==0)),"Observer failure cannot orphan an owned allocation");}
        using(var raster=(IDisposable)decode(Png(1,1,4,[zlib]),default,null)){VaultChecks.Require(!raster.GetType().GetProperties().Any(p=>p.PropertyType==typeof(byte[])||p.PropertyType.IsByRefLike),"No public raster raw accessor");VaultChecks.Require(Consume(raster,_=>VaultChecks.ExpectFailure(()=>Consume(raster,_=>{}),"Reentrant pixel callback refused")),"Outer pixel callback remains exclusive");}
        using(var raster=(IDisposable)decode(Png(1,1,4,[zlib]),default,null)){var owned=Owned(raster);raster.Dispose();raster.Dispose();VaultChecks.Require(owned.All(b=>b==0),"Unused raster disposal zeroes actual buffer idempotently");VaultChecks.ExpectFailure(()=>Consume(raster,_=>{}),"Disposed raster cannot borrow again");}
        using(var raster=(IDisposable)decode(Png(1,1,4,[zlib]),default,null)){var owned=Owned(raster);VaultChecks.Require(!Consume(raster,span=>{raster.Dispose();VaultChecks.Require(span.SequenceEqual(new byte[]{3,2,1,4}),"Self-dispose does not concurrently mutate borrowed raster");})&&owned.All(b=>b==0),"Raster self-dispose loses success and zeroes on callback exit");}
        using(var raster=(IDisposable)decode(Png(1,1,4,[zlib]),default,null)){var owned=Owned(raster);VaultChecks.ExpectFailure(()=>Consume(raster,_=>throw new IOException("Synthetic pixel consumer failure")),"Pixel callback failure");VaultChecks.Require(owned.All(b=>b==0),"Pixel callback failure zeroes exact raster");}
        using(var raster=(IDisposable)decode(Png(1,1,4,[zlib]),default,null)){var owned=Owned(raster);using var started=new ManualResetEventSlim();using var release=new ManualResetEventSlim();var task=Task.Run(()=>Consume(raster,span=>{started.Set();VaultChecks.Require(release.Wait(10000)&&span.SequenceEqual(new byte[]{3,2,1,4}),"Concurrent Dispose leaves exclusive pixel input unchanged");}));try{VaultChecks.Require(started.Wait(5000),"Paused pixel reader started");raster.Dispose();VaultChecks.Require(owned.SequenceEqual(new byte[]{3,2,1,4}),"Paused running pixels remain intact until callback exit");VaultChecks.ExpectFailure(()=>Consume(raster,_=>{}),"Concurrent/repeated pixel reader refused");}finally{release.Set();}VaultChecks.Require(!task.GetAwaiter().GetResult()&&owned.All(b=>b==0),"Concurrent disposed callback returns false then actual zero");}
        Console.WriteLine("PASS: strict bounded grayscale/gray-alpha/RGB/RGBA PNG pixels, five filters/exact BGRA/alpha, complete zlib/IDAT/output boundary and owned scratch/raster finally-zero (no preview UI)");
        void Reject(byte[] source,string reason){var copy=(byte[])source.Clone();var scratch=new List<byte[]>();bool refused=false;try{using var result=(IDisposable)decode(source,default,scratch.Add);}catch(InvalidDataException error){refused=true;VaultChecks.Require(error.Message=="Unsupported PNG preview pixels","Fixed non-sensitive pixel diagnostic");}VaultChecks.Require(refused,reason);VaultChecks.Require(source.SequenceEqual(copy)&&scratch.All(x=>x.All(b=>b==0)),"Refusal preserves source and zeroes every observed owned allocation");}
    }
    private static void ExpectCanceled(Action action,string reason){bool canceled=false;try{action();}catch(OperationCanceledException){canceled=true;}VaultChecks.Require(canceled,reason);}
    private static byte[] Owned(IDisposable raster)=>(byte[])raster.GetType().GetField("pixels",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(raster)!;
    private static int Scalar(object raster,string name)=>(int)raster.GetType().GetProperty(name)!.GetValue(raster)!;
    private static bool Consume(IDisposable raster,Pixels pixels){var method=raster.GetType().GetMethod("ConsumePixels")!;var callback=Delegate.CreateDelegate(method.GetParameters()[0].ParameterType,pixels.Target,pixels.Method);try{return (bool)method.Invoke(raster,[callback])!;}catch(TargetInvocationException error)when(error.InnerException is not null){ExceptionDispatchInfo.Capture(error.InnerException).Throw();throw;}}
    private static byte[] Bgra(byte[] samples,int channels)
    {
        var output=new byte[samples.Length/channels*4];
        for(int i=0;i<samples.Length/channels;i++)
        {
            int from=i*channels,to=i*4;
            if(channels<=2){output[to]=samples[from];output[to+1]=samples[from];output[to+2]=samples[from];output[to+3]=channels==2?samples[from+1]:(byte)255;}
            else{output[to]=samples[from+2];output[to+1]=samples[from+1];output[to+2]=samples[from];output[to+3]=channels==4?samples[from+3]:(byte)255;}
        }
        return output;
    }
    private static byte[] Filtered(byte[] original,int width,int height,int channels,int filter)
    {
        int stride=width*channels;var output=new byte[(stride+1)*height];for(int y=0;y<height;y++){output[y*(stride+1)]=(byte)filter;for(int x=0;x<stride;x++){int index=y*stride+x,a=x>=channels?original[index-channels]:0,b=y>0?original[index-stride]:0,c=y>0&&x>=channels?original[index-stride-channels]:0;int prediction=filter switch{0=>0,1=>a,2=>b,3=>(a+b)/2,4=>Paeth(a,b,c),_=>throw new Exception()};output[y*(stride+1)+1+x]=unchecked((byte)(original[index]-prediction));}}return output;
    }
    private static int Paeth(int a,int b,int c){int p=a+b-c;int da=Math.Abs(p-a),db=Math.Abs(p-b),dc=Math.Abs(p-c);return da<=db&&da<=dc?a:db<=dc?b:c;}
    private static byte[] Compress(byte[] input,CompressionLevel level){using var memory=new MemoryStream();using(var zlib=new ZLibStream(memory,level,true))zlib.Write(input);return memory.ToArray();}
    private static byte[] Png(int width,int height,int channels,byte[][] data){var header=new byte[13];BinaryPrimitives.WriteUInt32BigEndian(header,(uint)width);BinaryPrimitives.WriteUInt32BigEndian(header.AsSpan(4),(uint)height);header[8]=8;header[9]=(byte)(channels switch{1=>0,2=>4,3=>2,4=>6,_=>throw new ArgumentException()});using var stream=new MemoryStream();stream.Write([137,80,78,71,13,10,26,10]);Chunk("IHDR",header);foreach(var part in data)Chunk("IDAT",part);Chunk("IEND",[]);return stream.ToArray();void Chunk(string name,byte[] bytes){var chunk=new byte[bytes.Length+12];BinaryPrimitives.WriteUInt32BigEndian(chunk,(uint)bytes.Length);System.Text.Encoding.ASCII.GetBytes(name).CopyTo(chunk,4);bytes.CopyTo(chunk,8);uint crc=uint.MaxValue;foreach(byte b in chunk.AsSpan(4,bytes.Length+4)){crc^=b;for(int i=0;i<8;i++)crc=(crc&1)!=0?(crc>>1)^0xedb88320U:crc>>1;}BinaryPrimitives.WriteUInt32BigEndian(chunk.AsSpan(bytes.Length+8),crc^uint.MaxValue);stream.Write(chunk);}}
}
