using System.Reflection;
using System.Security.Cryptography;
using MemoApp.Core.Editing;
using MemoApp.Core.Storage;
internal static class SelectedBackupChecks
{
    internal static async Task Run()
    {
        await SelectedBackupFailureChecks.Run();
        string root=Path.Combine(Path.GetTempPath(),"memo-selected-backup-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);byte[] secret=EncryptedVault.GenerateRecoverySecret();
        try
        {
            const string opaque=" { \"nodes\" : [{\"type\":\"future-node\",\"opaque\":1e+03}] } ";var now=DateTimeOffset.UtcNow;var original=new StoredNote(Guid.NewGuid(),Guid.NewGuid(),[],now,now,"old backup","AUTHENTICATED_FUTURE_BODY","rich"){Document=new(1,opaque)};string path=Path.Combine(root,"vault");using(var seed=EncryptedVault.Create(path,secret,secret))seed.Save(new(4,Guid.NewGuid(),[original]));
            using var vault=EncryptedVault.Open(path,secret);using var active=new SaveCoordinator(vault,TimeProvider.System);var note=active.Workspace.Notes.Single();var folder=active.Workspace.CreateFolder("복원 folder");active.Workspace.MoveNote(note,folder.FolderId);active.Workspace.SetTags(note,["복원 tag"]);note.Favorite=true;Require(await active.PrepareAttachmentsAsync(),"Selected source root");byte[] objectBytes=[0,255,1,2,3];Guid objectId=active.AttachBytes(note,objectBytes,"원본.bin","application/octet-stream",note.EditVersion);var profile=Guid.NewGuid();active.Workspace.SetUiPreferences(profile,new(true,17,1.2));active.Workspace.RecordRecentNote(profile,note);active.Workspace.SaveSearch(profile,"보존 조건",new MemoApp.Core.Search.SearchOptions{Query="original"});Require(await active.SaveAsync(),"Selected source saved");string backup=Path.Combine(root,"source.vault");Require(await active.BackupAsync(backup),"Actual selected source backup");byte[] cipher=File.ReadAllBytes(backup);var method=typeof(SaveCoordinator).GetMethod("ImportSelectedEncryptedBackup")??throw new Exception("Selected encrypted backup import is missing");
            NoteDraft[] Import(byte[] bytes,Guid[] ids,long? epoch=null){try{return (NoteDraft[])method.Invoke(active,[bytes,ids,epoch??active.AttachmentPreviewEpoch])!;}catch(TargetInvocationException e)when(e.InnerException is not null){System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e.InnerException).Throw();throw;}}
            note.Title="CURRENT original retained";Require(await active.SaveAsync(),"Existing current accepted");var before=active.Workspace.Capture();byte[] current=File.ReadAllBytes(Path.Combine(path,"current.vault"));long epoch=active.AttachmentPreviewEpoch;
            VaultChecks.ExpectFailure(()=>Import(cipher,[note.Id],epoch-1),"Stale selected authority refused");VaultChecks.ExpectFailure(()=>Import(cipher,[note.Id,note.Id]),"Duplicate selected IDs refused");VaultChecks.ExpectFailure(()=>Import(cipher,[Guid.NewGuid()]),"Missing source ID refused");
            byte[] alternateRoot=RandomNumberGenerator.GetBytes(32),alternateVault=RandomNumberGenerator.GetBytes(32);try
            {
                var wrong=AttachmentObjectCodec.Encrypt(objectBytes,active.VaultIdentity,before.AttachmentRootId,alternateRoot,"different.bin","application/octet-stream");var altered=new VaultSnapshot(5,before.DeviceId,[original with{AttachmentIds=[wrong.ObjectId]}]){AttachmentRootId=before.AttachmentRootId,AttachmentObjects=[wrong]};byte[] plain=SnapshotSerialization.Bytes(altered);try{byte[] forged=AttachmentEnvelope.Encrypt(plain,alternateVault,secret,new(active.VaultIdentity,Guid.NewGuid(),Guid.NewGuid(),1,3,plain.Length),before.AttachmentRootId,alternateRoot);Require(active.PreviewEncryptedBackup(forged).Notes.Length==1,"Same vault/root-ID alternate-key envelope is genuinely authenticated by backup secret");bool refused=false;try{Import(forged,[original.NoteId]);}catch(CryptographicException){refused=true;}Require(refused&&SnapshotSerialization.Bytes(active.Workspace.Capture()).SequenceEqual(SnapshotSerialization.Bytes(before))&&current.SequenceEqual(File.ReadAllBytes(Path.Combine(path,"current.vault"))),"Current-root authentication refuses alternate key before ANY workspace mutation");}finally{CryptographicOperations.ZeroMemory(plain);}
            }
            finally{CryptographicOperations.ZeroMemory(alternateRoot);CryptographicOperations.ZeroMemory(alternateVault);}
            int changed=0;Action whole=()=>{changed++;Require(active.Workspace.Notes.Count==2,"Observers see complete selected batch");};active.Workspace.Changed+=whole;NoteDraft[] copies;try{copies=Import(cipher,[note.Id]);}finally{active.Workspace.Changed-=whole;}
            var copy=copies.Single();var after=active.Workspace.Capture();Require(System.Text.Json.JsonSerializer.Serialize(after.UiDevices)==System.Text.Json.JsonSerializer.Serialize(before.UiDevices)&&after.History.SequenceEqual(before.History)&&after.AttachmentObjects.All(o=>before.AttachmentObjects.Any(old=>AttachmentValidation.SameObject(old,o))),"Original histories/UI/recent/search/immutable objects remain exact");Require(changed==1&&copy.Id!=note.Id&&copy.Title=="old backup"&&copy.Text==original.Text&&copy.Document!.SourceJson==opaque&&copy.Favorite&&copy.FolderId==folder.FolderId&&copy.AttachmentIds.Single()==objectId&&note.Title=="CURRENT original retained","Fresh selected copy preserves authenticated opaque source/metadata/attachments while current remains unchanged");var parent=new StoredFolder(Guid.NewGuid(),null,"backup-only parent");var child=new StoredFolder(Guid.NewGuid(),parent.FolderId,"backup-only child");var extraTag=new StoredTag(Guid.NewGuid(),"backup-only tag");var extraSource=original with{NoteId=Guid.NewGuid(),RevisionId=Guid.NewGuid(),Metadata=new(){FolderId=child.FolderId,TagIds=[extraTag.TagId]},AttachmentIds=[objectId]};var extraSnapshot=new VaultSnapshot(5,before.DeviceId,[extraSource]){Folders=[parent,child],Tags=[extraTag],AttachmentRootId=before.AttachmentRootId,AttachmentObjects=before.AttachmentObjects};byte[] extraPlain=SnapshotSerialization.Bytes(extraSnapshot);Guid organizationCopy,organizationObject=Guid.Empty;byte[] organizationBytes=[7,0,255,4];
            try{byte[] rootKey=(byte[])typeof(EncryptedVault).GetField("attachmentRootKey",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(vault)!;byte[] vaultKey=(byte[])typeof(EncryptedVault).GetField("vaultKey",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(vault)!;var incomingObject=AttachmentObjectCodec.Encrypt(organizationBytes,active.VaultIdentity,before.AttachmentRootId,rootKey,"backup-only.bin","application/octet-stream");organizationObject=incomingObject.ObjectId;extraSnapshot=extraSnapshot with{Notes=[extraSource with{AttachmentIds=[organizationObject]}],AttachmentObjects=before.AttachmentObjects.Add(incomingObject)};CryptographicOperations.ZeroMemory(extraPlain);extraPlain=SnapshotSerialization.Bytes(extraSnapshot);byte[] extraCipher=AttachmentEnvelope.Encrypt(extraPlain,vaultKey,secret,new(active.VaultIdentity,Guid.NewGuid(),Guid.NewGuid(),1,3,extraPlain.Length),before.AttachmentRootId,rootKey);organizationCopy=Import(extraCipher,[extraSource.NoteId]).Single().Id;Require(active.Workspace.Folders.Contains(parent)&&active.Workspace.Folders.Contains(child)&&active.Workspace.Tags.Contains(extraTag),"Backup-only ancestors/tag are published into live organization before save");}finally{CryptographicOperations.ZeroMemory(extraPlain);}
            Require(await active.SaveAsync(),"Selected copy encrypted commit");Guid freshId=copy.Id;await active.LockAsync();active.Dispose();
            using var reopened=new SaveCoordinator(EncryptedVault.Open(path,secret),TimeProvider.System);var restored=reopened.Workspace.Notes.Single(n=>n.Id==freshId);byte[] bytes=reopened.ReadAttachmentBytes(restored,objectId,restored.EditVersion);try{Require(bytes.SequenceEqual(objectBytes)&&restored.Document!.SourceJson==opaque&&reopened.Workspace.Notes.Count==3&&cipher.SequenceEqual(File.ReadAllBytes(backup)),"Selected copy and exact attachment restart, original backup unchanged");}finally{CryptographicOperations.ZeroMemory(bytes);}var organized=reopened.Workspace.Notes.Single(n=>n.Id==organizationCopy);byte[] newBytes=reopened.ReadAttachmentBytes(organized,organizationObject,organized.EditVersion);try{Require(newBytes.SequenceEqual(organizationBytes),"Backup-only authenticated object is actually restored under current root key");}finally{CryptographicOperations.ZeroMemory(newBytes);}
            Require(reopened.Workspace.Notes.Single(n=>n.Id==organizationCopy).FolderId==child.FolderId&&reopened.Workspace.Folders.Contains(parent)&&reopened.Workspace.Folders.Contains(child)&&reopened.Workspace.Tags.Contains(extraTag),"Backup-only organization refs survive actual encrypted restart");await reopened.LockAsync();
            Console.WriteLine("PASS: selected fresh encrypted copy with exact opaque source/metadata/attachment restart and current-root-key rejection before mutation");
        }
        finally{CryptographicOperations.ZeroMemory(secret);Directory.Delete(root,true);}
    }
    private static void Require(bool value,string message)=>VaultChecks.Require(value,message);
}
